<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by id_admin
     */
    function get_admin($id_admin)
    {
        return $this->db->get_where('admin',array('id_admin'=>$id_admin))->row_array();
    }

    function get_admin_byuname($username)
    {
        return $this->db->get_where('admin',array('username'=>$username))->row_array();
    }

    function login($u,$p)
    {
        $q = $this->db->where("username",$u)
                ->where("password",$p)
                ->get("admin")
                ->num_rows();
        return ($q>0); 
    }
    
    /*
     * Get all admin
     */
    function get_all_admin()
    {
        return $this->db->get('admin')->result_array();
    }
    
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('admin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($id_admin,$params)
    {
        $this->db->where('id_admin',$id_admin);
        $response = $this->db->update('admin',$params);
        if($response)
        {
            return "admin updated successfully";
        }
        else
        {
            return "Error occuring while updating admin";
        }
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($id_admin)
    {
        $response = $this->db->delete('admin',array('id_admin'=>$id_admin));
        if($response)
        {
            return "admin deleted successfully";
        }
        else
        {
            return "Error occuring while deleting admin";
        }
    }
}
