<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Donasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get donasi by id_donasi
     */
    function get_donasi($id_donasi)
    {
        return $this->db->get_where('donasi',array('id_donasi'=>$id_donasi))->row_array();
    }

    function get_donasi_bydonatur($id_donatur)
    {
        return $this->db->get_where('donasi',array('id_donatur'=>$id_donatur,'status'=>'Y'))->result_array();
    }
    
    /*
     * Get all donasi
     */
    function get_all_donasi()
    {
        return $this->db
            ->join('donatur b','a.id_donatur=b.id_donatur')
            ->get('donasi a')->result_array();
    }
    
    /*
     * function to add new donasi
     */
    function add_donasi($params)
    {
        $this->db->insert('donasi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update donasi
     */
    function update_donasi($id_donasi,$params)
    {
        $this->db->where('id_donasi',$id_donasi);
        $response = $this->db->update('donasi',$params);
        if($response)
        {
            return "donasi updated successfully";
        }
        else
        {
            return "Error occuring while updating donasi";
        }
    }
    
    /*
     * function to delete donasi
     */
    function delete_donasi($id_donasi)
    {
        $response = $this->db->delete('donasi',array('id_donasi'=>$id_donasi));
        if($response)
        {
            return "donasi deleted successfully";
        }
        else
        {
            return "Error occuring while deleting donasi";
        }
    }

    function get_lastdonasi($limit = 3){
        $q = $this->db->query("SELECT * FROM donasi a
            INNER JOIN donatur b ON a.id_donatur=b.id_donatur
            WHERE a.status='Y'
            ORDER BY a.tanggal_donasi DESC
            LIMIT 0,".$limit)->result_array();
        return $q;
    }
}
