<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Donatur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get donatur by id_donatur
     */
    function get_donatur($id_donatur)
    {
        return $this->db->get_where('donatur',array('id_donatur'=>$id_donatur))->row_array();
    }

    function get_donatur_byuser($user)
    {
        return $this->db->get_where('donatur',array('username'=>$user))->row_array();
    }
    
    /*
     * Get all donatur
     */
    function get_all_donatur()
    {
        return $this->db->get('donatur')->result_array();
    }
    
    /*
     * function to add new donatur
     */
    function add_donatur($params)
    {
        $this->db->insert('donatur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update donatur
     */
    function update_donatur($id_donatur,$params)
    {
        $this->db->where('id_donatur',$id_donatur);
        $response = $this->db->update('donatur',$params);
        if($response)
        {
            return "donatur updated successfully";
        }
        else
        {
            return "Error occuring while updating donatur";
        }
    }
    
    /*
     * function to delete donatur
     */
    function delete_donatur($id_donatur)
    {
        $response = $this->db->delete('donatur',array('id_donatur'=>$id_donatur));
        if($response)
        {
            return "donatur deleted successfully";
        }
        else
        {
            return "Error occuring while deleting donatur";
        }
    }

    function cek_login($u,$p)
    {
        $q = $this->db->where("username",$u)
                ->where("password",$p)
                ->get("donatur")
                ->num_rows();
        return ($q>0);    
    }
}
