<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Galeri_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get galeri by id
     */
    function get_galeri($id)
    {
        return $this->db->get_where('galeri',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all galeri
     */
    function get_all_galeri()
    {
        return $this->db->get('galeri')->result_array();
    }
    
    /*
     * function to add new galeri
     */
    function add_galeri($params)
    {
        $this->db->insert('galeri',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update galeri
     */
    function update_galeri($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('galeri',$params);
        if($response)
        {
            return "galeri updated successfully";
        }
        else
        {
            return "Error occuring while updating galeri";
        }
    }
    
    /*
     * function to delete galeri
     */
    function delete_galeri($id)
    {
        $response = $this->db->delete('galeri',array('id'=>$id));
        if($response)
        {
            return "galeri deleted successfully";
        }
        else
        {
            return "Error occuring while deleting galeri";
        }
    }
}
