<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Kontak_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kontak by id_kontak
     */
    function get_kontak($id_kontak)
    {
        return $this->db->get_where('kontak',array('id_kontak'=>$id_kontak))->row_array();
    }
    
    /*
     * Get all kontak
     */
    function get_all_kontak()
    {
        return $this->db->get('kontak')->result_array();
    }
    
    /*
     * function to add new kontak
     */
    function add_kontak($params)
    {
        $this->db->insert('kontak',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kontak
     */
    function update_kontak($id_kontak,$params)
    {
        $this->db->where('id_kontak',$id_kontak);
        $response = $this->db->update('kontak',$params);
        if($response)
        {
            return "kontak updated successfully";
        }
        else
        {
            return "Error occuring while updating kontak";
        }
    }
    
    /*
     * function to delete kontak
     */
    function delete_kontak($id_kontak)
    {
        $response = $this->db->delete('kontak',array('id_kontak'=>$id_kontak));
        if($response)
        {
            return "kontak deleted successfully";
        }
        else
        {
            return "Error occuring while deleting kontak";
        }
    }
}
