<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Transaksi_pengeluaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get transaksi_pengeluaran by id_trans
     */
    function get_transaksi_pengeluaran($id_trans)
    {
        return $this->db->get_where('transaksi_pengeluaran',array('id_trans'=>$id_trans))->row_array();
    }
    
    /*
     * Get all transaksi_pengeluaran
     */
    function get_all_transaksi_pengeluaran()
    {
        return $this->db->get('transaksi_pengeluaran')->result_array();
    }
    
    /*
     * function to add new transaksi_pengeluaran
     */
    function add_transaksi_pengeluaran($params)
    {
        $this->db->insert('transaksi_pengeluaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update transaksi_pengeluaran
     */
    function update_transaksi_pengeluaran($id_trans,$params)
    {
        $this->db->where('id_trans',$id_trans);
        $response = $this->db->update('transaksi_pengeluaran',$params);
        if($response)
        {
            return "transaksi_pengeluaran updated successfully";
        }
        else
        {
            return "Error occuring while updating transaksi_pengeluaran";
        }
    }
    
    /*
     * function to delete transaksi_pengeluaran
     */
    function delete_transaksi_pengeluaran($id_trans)
    {
        $response = $this->db->delete('transaksi_pengeluaran',array('id_trans'=>$id_trans));
        if($response)
        {
            return "transaksi_pengeluaran deleted successfully";
        }
        else
        {
            return "Error occuring while deleting transaksi_pengeluaran";
        }
    }

    
}
