<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Anak_asuh extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->cek_session();
        $this->load->model('Anak_asuh_model');
    } 

    private function cek_session()
    {
        if(!($this->session->userdata("admin_in")=="Y")){
            redirect("admin/login");
        }
    }

    /*
     * Listing of anak_asuh
     */
    function index()
    {
        $data['anak_asuh'] = $this->Anak_asuh_model->get_all_anak_asuh();

        $data['_view'] = 'anak_asuh/index';
        $this->load->view('layouts/main',$data);
    }

    private function upload_foto()
    {
        $this->load->library('upload');
        $config = array(
            'upload_path' => "./upload/",
            'allowed_types' => "jpg|png|jpeg",
            'overwrite' => TRUE,
            );

        $this->upload->initialize($config);
        $src_file = null;
        if($this->upload->do_upload('foto')){
            $upload_data = $this->upload->data();
            $file_name = $upload_data['file_name'];
            $src_file = "upload/".$file_name;
            return $src_file;
        }
        else{
            return "ERROR|".$this->upload->display_errors();
        }
    }

    /*
     * Adding a new anak_asuh
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','max_length[30]|required');
		$this->form_validation->set_rules('alamat','Alamat','max_length[50]|required');
		$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','required');
		$this->form_validation->set_rules('tanggal_lahir','Tanggal Lahir','required');
		
		if($this->form_validation->run())     
        {   
            //print_r($_POST);
            $params = array(
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'nama' => $this->input->post('nama'),
				'tanggal_lahir' => $this->input->post('tanggal_lahir'),
				//'foto' => $foto,
				'alamat' => $this->input->post('alamat'),
            );
            $foto = $this->upload_foto();
            $ex = explode("|", $foto);
            if($ex[0]!="ERROR"){
                $params['foto'] = $foto;
            }
            
            $anak_asuh_id = $this->Anak_asuh_model->add_anak_asuh($params);
            redirect('admin/anak_asuh/index');
        }
        else
        {            
            $data['_view'] = 'anak_asuh/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a anak_asuh
     */
    function edit($id_anak_asuh)
    {   
        // check if the anak_asuh exists before trying to edit it
        $data['anak_asuh'] = $this->Anak_asuh_model->get_anak_asuh($id_anak_asuh);
        
        if(isset($data['anak_asuh']['id_anak_asuh']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','max_length[30]|required');
			$this->form_validation->set_rules('alamat','Alamat','max_length[50]|required');
			$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','required');
			$this->form_validation->set_rules('tanggal_lahir','Tanggal Lahir','required');
		
			if($this->form_validation->run())     
            {   
                $foto = $this->upload_foto();
                $params = array(
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'nama' => $this->input->post('nama'),
					'tanggal_lahir' => $this->input->post('tanggal_lahir'),
//					'foto' => $foto,
					'alamat' => $this->input->post('alamat'),
                );
                $ex = explode("|", $foto);
                if($ex[0]!="ERROR"){
                    $params['foto'] = $foto;
                }
                $this->Anak_asuh_model->update_anak_asuh($id_anak_asuh,$params);     
                redirect('admin/anak_asuh/index');
            }
            else
            {
                $data['_view'] = 'anak_asuh/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The anak_asuh you are trying to edit does not exist.');
    } 

    /*
     * Deleting anak_asuh
     */
    function remove($id_anak_asuh)
    {
        $anak_asuh = $this->Anak_asuh_model->get_anak_asuh($id_anak_asuh);

        // check if the anak_asuh exists before trying to delete it
        if(isset($anak_asuh['id_anak_asuh']))
        {
            $this->Anak_asuh_model->delete_anak_asuh($id_anak_asuh);
            redirect('admin/anak_asuh/index');
        }
        else
            show_error('The anak_asuh you are trying to delete does not exist.');
    }
    
}
