<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Donasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->cek_session();
        $this->load->model('Donasi_model');
    } 

      private function cek_session()
    {
        if(!($this->session->userdata("admin_in")=="Y")){
            redirect("admin/login");
        }
    }


    /*
     * Listing of donasi
     */
    function index()
    {
        $data['donasi'] = $this->Donasi_model->get_all_donasi();

        $data['_view'] = 'donasi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new donasi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_donatur','Id Donatur','integer|required');
		$this->form_validation->set_rules('jumlah_donasi','Jumlah Donasi','integer|required|greater_than[0]');
		$this->form_validation->set_rules('keterangan_donasi','Keterangan Donasi','max_length[50]|required');
		$this->form_validation->set_rules('bukti_resi','Bukti Resi','max_length[30]');
		$this->form_validation->set_rules('tanggal_donasi','Tanggal Donasi','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_donatur' => $this->input->post('id_donatur'),
				'jumlah_donasi' => $this->input->post('jumlah_donasi'),
				'bukti_resi' => $this->input->post('bukti_resi'),
				'tanggal_donasi' => $this->input->post('tanggal_donasi'),
				'keterangan_donasi' => $this->input->post('keterangan_donasi'),
            );
            
            $donasi_id = $this->Donasi_model->add_donasi($params);
            redirect('admin/donasi/index');
        }
        else
        {
			$this->load->model('Donatur_model');
			$data['all_donatur'] = $this->Donatur_model->get_all_donatur();
            
            $data['_view'] = 'donasi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a donasi
     */
    function edit($id_donasi)
    {   
        // check if the donasi exists before trying to edit it
        $data['donasi'] = $this->Donasi_model->get_donasi($id_donasi);
        
        if(isset($data['donasi']['id_donasi']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_donatur','Id Donatur','integer|required');
			$this->form_validation->set_rules('jumlah_donasi','Jumlah Donasi','integer|required|greater_than[0]');
			$this->form_validation->set_rules('keterangan_donasi','Keterangan Donasi','max_length[50]|required');
			$this->form_validation->set_rules('bukti_resi','Bukti Resi','max_length[30]');
			$this->form_validation->set_rules('tanggal_donasi','Tanggal Donasi','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_donatur' => $this->input->post('id_donatur'),
					'jumlah_donasi' => $this->input->post('jumlah_donasi'),
					'bukti_resi' => $this->input->post('bukti_resi'),
					'tanggal_donasi' => $this->input->post('tanggal_donasi'),
					'keterangan_donasi' => $this->input->post('keterangan_donasi'),
                );

                $this->Donasi_model->update_donasi($id_donasi,$params);            
                redirect('admin/donasi/index');
            }
            else
            {
				$this->load->model('Donatur_model');
				$data['all_donatur'] = $this->Donatur_model->get_all_donatur();

                $data['_view'] = 'donasi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The donasi you are trying to edit does not exist.');
    } 

    function validasi($id_donasi)
    {
        $this->db->query("UPDATE donasi SET status='Y' where id_donasi='".$id_donasi."'");
        redirect('admin/donasi/index');
    }

    function batal_validasi($id_donasi)
    {
        $this->db->query("UPDATE donasi SET status='N' where id_donasi='".$id_donasi."'");
        redirect('admin/donasi/index');
    }

    /*
     * Deleting donasi
     */
    function remove($id_donasi)
    {
        $donasi = $this->Donasi_model->get_donasi($id_donasi);

        // check if the donasi exists before trying to delete it
        if(isset($donasi['id_donasi']))
        {
            $this->Donasi_model->delete_donasi($id_donasi);
            redirect('admin/donasi/index');
        }
        else
            show_error('The donasi you are trying to delete does not exist.');
    }
    
}
