<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Donatur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->cek_session();
        $this->load->model('Donatur_model');
    } 
  private function cek_session()
    {
        if(!($this->session->userdata("admin_in")=="Y")){
            redirect("admin/login");
        }
    }

    /*
     * Listing of donatur
     */
    function index()
    {
        $data['donatur'] = $this->Donatur_model->get_all_donatur();

        $data['_view'] = 'donatur/index';
        $this->load->view('layouts/main',$data);
    }

    private function upload_foto()
    {
        $this->load->library('upload');
        $config = array(
            'upload_path' => "./upload/",
            'allowed_types' => "jpg|png|jpeg",
            'overwrite' => TRUE,
            );

        $this->upload->initialize($config);
        $src_file = null;
        if($this->upload->do_upload('foto')){
            $upload_data = $this->upload->data();
            $file_name = $upload_data['file_name'];
            $src_file = "upload/".$file_name;
            return $src_file;
        }
        else{
            return "ERROR|".$this->upload->display_errors();
        }
    }


    /*
     * Adding a new donatur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','max_length[30]|required|min_length[6]');
		$this->form_validation->set_rules('username','Username','max_length[20]|required');
		$this->form_validation->set_rules('nama_donatur','Nama Donatur','max_length[30]|required');
		$this->form_validation->set_rules('email','Email','max_length[30]|valid_email');
		$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','max_length[10]');
		$this->form_validation->set_rules('cp','Cp','max_length[15]|numeric');
		$this->form_validation->set_rules('alamat','Alamat','max_length[50]');
		$this->form_validation->set_rules('foto_donatur','Foto Donatur','max_length[40]');
		
		if($this->form_validation->run())     
        {   
            $tgl = $this->input->post('tanggal_daftar');
            $ex = explode('-', $tgl);
            $tgl = $ex[2].'/'.$ex[1].'/'.$ex[0];
            $params = array(
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
				'nama_donatur' => $this->input->post('nama_donatur'),
				'email' => $this->input->post('email'),
				'cp' => $this->input->post('cp'),
				'alamat' => $this->input->post('alamat'),
				//'foto_donatur' => $this->input->post('foto_donatur'),
				'tanggal_daftar' => $tgl,
            );

            $foto = $this->upload_foto();
            $ex = explode("|", $foto);
            if($ex[0]!="ERROR"){
                $params['foto_donatur'] = $foto;
            }
            
            $donatur_id = $this->Donatur_model->add_donatur($params);
            redirect('admin/donatur/index');
        }
        else
        {            
            $data['_view'] = 'donatur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a donatur
     */
    function edit($id_donatur)
    {   
        // check if the donatur exists before trying to edit it
        $data['donatur'] = $this->Donatur_model->get_donatur($id_donatur);
        
        if(isset($data['donatur']['id_donatur']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','max_length[30]|required|min_length[6]');
			$this->form_validation->set_rules('username','Username','max_length[20]|required');
			$this->form_validation->set_rules('nama_donatur','Nama Donatur','max_length[30]|required');
			$this->form_validation->set_rules('email','Email','max_length[30]|valid_email');
			$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','max_length[10]');
			$this->form_validation->set_rules('cp','Cp','max_length[15]|numeric');
			$this->form_validation->set_rules('alamat','Alamat','max_length[50]');
			$this->form_validation->set_rules('foto_donatur','Foto Donatur','max_length[40]');
		
			if($this->form_validation->run())     
            {   
                $tgl = $this->input->post('tanggal_daftar');
                $ex = explode('-', $tgl);
                $tgl = $ex[2].'/'.$ex[1].'/'.$ex[0];
                $params = array(
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
					'nama_donatur' => $this->input->post('nama_donatur'),
					'email' => $this->input->post('email'),
					'cp' => $this->input->post('cp'),
					'alamat' => $this->input->post('alamat'),
					//'foto_donatur' => $this->input->post('foto_donatur'),
					'tanggal_daftar' => $tgl,
                );

                $foto = $this->upload_foto();
                $ex = explode("|", $foto);
                if($ex[0]!="ERROR"){
                    $params['foto_donatur'] = $foto;
                }

                $this->Donatur_model->update_donatur($id_donatur,$params);            
                redirect('admin/donatur/index');
            }
            else
            {
                $data['_view'] = 'donatur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The donatur you are trying to edit does not exist.');
    } 

    /*
     * Deleting donatur
     */
    function remove($id_donatur)
    {
        $donatur = $this->Donatur_model->get_donatur($id_donatur);

        // check if the donatur exists before trying to delete it
        if(isset($donatur['id_donatur']))
        {
            $this->Donatur_model->delete_donatur($id_donatur);
            redirect('admin/donatur/index');
        }
        else
            show_error('The donatur you are trying to delete does not exist.');
    }
    
}
