<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Galeri extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->cek_session();
        $this->load->model('Galeri_model');
    } 
    private function cek_session()
    {
        if(!($this->session->userdata("admin_in")=="Y")){
            redirect("admin/login");
        }
    }

    /*
     * Listing of galeri
     */
    function index()
    {
        $data['galeri'] = $this->Galeri_model->get_all_galeri();

        $data['_view'] = 'galeri/index';
        $this->load->view('layouts/main',$data);
    }

    private function upload_foto()
    {
        $this->load->library('upload');
        $config = array(
            'upload_path' => "./upload/galeri/",
            'allowed_types' => "jpg|png|jpeg",
            'overwrite' => TRUE,
            );

        $this->upload->initialize($config);
        if (!is_dir('upload')) {
            mkdir('./upload',0777,TRUE);
        }
        if (!is_dir('upload/galeri')) {
            mkdir('./upload/galeri',0777,TRUE);
        }

        $src_file = null;
        if($this->upload->do_upload('foto')){
            $upload_data = $this->upload->data();
            $file_name = $upload_data['file_name'];
            $src_file = "upload/galeri/".$file_name;
            return $src_file;
        }
        else{
            return "ERROR|".$this->upload->display_errors();
        }
    }


    /*
     * Adding a new galeri
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('ket','Nama galeri','max_length[100]|required');

        if($this->form_validation->run())     
        {   
            $params = array(
                'ket' => $this->input->post('ket'),
				//'src' => $this->input->post('src'),
                );

            $foto = $this->upload_foto();
            $ex = explode("|", $foto);
            if($ex[0]!="ERROR"){
                $params['src'] = $foto;
            }
            
            $galeri_id = $this->Galeri_model->add_galeri($params);
            redirect('admin/galeri/index');
        }
        else
        {            
            $data['_view'] = 'galeri/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a galeri
     */
    function edit($id)
    {   
        // check if the galeri exists before trying to edit it
        $data['galeri'] = $this->Galeri_model->get_galeri($id);
        
        if(isset($data['galeri']['id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('ket','Nama galeri','max_length[100]|required');

            if($this->form_validation->run())     
            {   
                $params = array(
                    'ket' => $this->input->post('ket'),
                    //'src' => $this->input->post('src'),
                   );

                $foto = $this->upload_foto();
                $ex = explode("|", $foto);
                if($ex[0]!="ERROR"){
                    $params['src'] = $foto;
                }

                $this->Galeri_model->update_galeri($id,$params);            
                redirect('admin/galeri/index');
            }
            else
            {
                $data['_view'] = 'galeri/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The galeri you are trying to edit does not exist.');
    } 

    /*
     * Deleting galeri
     */
    function remove($id)
    {
        $galeri = $this->Galeri_model->get_galeri($id);

        // check if the galeri exists before trying to delete it
        if(isset($galeri['id']))
        {
            $this->Galeri_model->delete_galeri($id);
            redirect('admin/galeri/index');
        }
        else
            show_error('The galeri you are trying to delete does not exist.');
    }
    
}
