<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Kontak extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->cek_session();
        $this->load->model('Kontak_model');
    } 
  private function cek_session()
    {
        if(!($this->session->userdata("admin_in")=="Y")){
            redirect("admin/login");
        }
    }
    /*
     * Listing of kontak
     */
    function index()
    {
        $data['kontak'] = $this->Kontak_model->get_all_kontak();

        $data['_view'] = 'kontak/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kontak
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','max_length[9]|required');
		$this->form_validation->set_rules('email','Email','max_length[50]|valid_email|required');
		$this->form_validation->set_rules('pesan','Pesan','required|min_length[5]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'email' => $this->input->post('email'),
				'pesan' => $this->input->post('pesan'),
            );
            
            $kontak_id = $this->Kontak_model->add_kontak($params);
            redirect('admin/kontak/index');
        }
        else
        {            
            $data['_view'] = 'kontak/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kontak
     */
    function edit($id_kontak)
    {   
        // check if the kontak exists before trying to edit it
        $data['kontak'] = $this->Kontak_model->get_kontak($id_kontak);
        
        if(isset($data['kontak']['id_kontak']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','max_length[9]|required');
			$this->form_validation->set_rules('email','Email','max_length[50]|valid_email|required');
			$this->form_validation->set_rules('pesan','Pesan','required|min_length[5]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'email' => $this->input->post('email'),
					'pesan' => $this->input->post('pesan'),
                );

                $this->Kontak_model->update_kontak($id_kontak,$params);            
                redirect('admin/kontak/index');
            }
            else
            {
                $data['_view'] = 'kontak/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kontak you are trying to edit does not exist.');
    } 

    /*
     * Deleting kontak
     */
    function remove($id_kontak)
    {
        $kontak = $this->Kontak_model->get_kontak($id_kontak);

        // check if the kontak exists before trying to delete it
        if(isset($kontak['id_kontak']))
        {
            $this->Kontak_model->delete_kontak($id_kontak);
            redirect('admin/kontak/index');
        }
        else
            show_error('The kontak you are trying to delete does not exist.');
    }
    
}
