<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Rekap_keuangan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->cek_session();
        $this->load->model('Transaksi_pengeluaran_model');
    } 

      private function cek_session()
    {
        if(!($this->session->userdata("admin_in")=="Y")){
            redirect("admin/login");
        }
    }

    /*
     * Listing of transaksi_pengeluaran
     */
    function index()
    {
        if ($_POST) {
            $tgl1 = $this->input->post('tgl1');
            $tgl2 = $this->input->post('tgl2');
            $ex = explode('-', $tgl1);
            $tgl1 = $ex[2].'/'.$ex[1].'/'.$ex[0];
            $ex = explode('-', $tgl2);
            $tgl2 = $ex[2].'/'.$ex[1].'/'.$ex[0];
        } else {
            $tgl1 = date('Y/m/d');
            $tgl2 = date('Y/m/d');
        }

        $data['rekap_keuangan'] = $this->db->query("SELECT * FROM (
SELECT a.tanggal_donasi tgl, a.keterangan_donasi ket, a.jumlah_donasi debit, 0 kredit FROM donasi a
WHERE a.status='Y'
UNION ALL
SELECT b.tanggal_transaksi tgl, b.keterangan_donasi ket, 0 debit, b.besar_pengeluaran kredit FROM transaksi_pengeluaran b
) c
WHERE c.tgl BETWEEN '$tgl1' AND '$tgl2'")
        ->result_array();
        $data['_view'] = 'rekap_keuangan/index';
        $this->load->view('layouts/main',$data);
    }
    
}
